### ISSUE TITLE
PHP 8.0 or higher causes a fatal error email

### ISSUE THREAD

**Issue by michaelbeil** [strangerstudios/pmpro-courses#38]
**Describe the bug**
When you click the “Edit” button next to to a block, a fatal error email will be sent

**To Reproduce**
Steps to reproduce the behavior on customer site:
1. Install Courses for Membership Add On
2. Set PHP version to PHP 8.0 or higher, click the “Edit” button next to the block, the following email will be sent:

> Since WordPress 5.2 there is a built-in feature that detects when a plugin or theme causes a fatal error on your site, and notifies you with this automated email.
> 
> In this case, WordPress caught an error with one of your plugins, Paid Memberships Pro – Courses for Membership Add On.
> 
> First, visit your website (http://domain.com/) and check for any visible issues. Next, visit the page where the error was caught (http://domain.com/wp-json/jetpack/v4/sync/spawn-sync?time=1661219907&request_lock_id=1661219907.7152) and check for any visible issues.
> 
> Please contact your host for assistance with investigating this issue further.
> 
> If your site appears broken and you can’t access your dashboard normally, WordPress now has a special “recovery mode”. This lets you safely login to your dashboard and investigate further.
> 
> When seeking help with this issue, you may be asked for some of the following information:
> WordPress version 6.0.1
> Active theme: Divi (version 4.18.0)
> Current plugin: Paid Memberships Pro – Courses for Membership Add On (version 1.1)
> PHP version 8.1.8
> 
> Error Details

```
=============
An error of type E_ERROR was caused in line 52 of the file /home/x/public_html/wp-content/plugins/pmpro-courses/includes/admin.php. Error message: Uncaught TypeError: array_merge(): Argument #1 must be of type array, null given in /home/x/public_html/wp-content/plugins/pmpro-courses/includes/admin.php:52
Stack trace:
#0 /home/x/public_html/wp-content/plugins/pmpro-courses/includes/admin.php(52): array_merge()
#1 /home/x/public_html/wp-includes/class-wp-hook.php(309): pmpro_courses_plugin_action_links()
#2 /home/x/public_html/wp-includes/plugin.php(191): WP_Hook->apply_filters()
#3 /home/x/public_html/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-sync/src/modules/class-callables.php(380): apply_filters()
#4 /home/x/public_html/wp-includes/class-wp-hook.php(307): Automattic\Jetpack\Sync\Modules\Callables->set_plugin_action_links()
#5 /home/x/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#6 /home/x/public_html/wp-includes/plugin.php(476): WP_Hook->do_action()
#7 /home/x/public_html/wp-admin/includes/class-wp-screen.php(422): do_action()
#8 /home/x/public_html/wp-admin/includes/screen.php(243): WP_Screen->set_current_screen()
#9 /home/x/public_html/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-sync/src/class-sender.php(471): set_current_screen()
#10 /home/x/public_html/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-sync/src/class-sender.php(567): Automattic\Jetpack\Sync\Sender->get_items_to_send()
#11 /home/x/public_html/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-sync/src/class-sender.php(428): Automattic\Jetpack\Sync\Sender->do_sync_for_queue()
#12 /home/x/public_html/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-sync/src/class-sender.php(370): Automattic\Jetpack\Sync\Sender->do_sync_and_set_delays()
#13 /home/x/public_html/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-sync/src/class-actions.php(191): Automattic\Jetpack\Sync\Sender->do_dedicated_sync_and_exit()
#14 /home/x/public_html/wp-includes/class-wp-hook.php(307): Automattic\Jetpack\Sync\Actions::add_dedicated_sync_sender_init()
#15 /home/x/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#16 /home/x/public_html/wp-includes/plugin.php(476): WP_Hook->do_action()
#17 /home/x/public_html/wp-settings.php(598): do_action()
#18 /home/x/public_html/wp-config.php(111): require_once(‘/home/x…’)
#19 /home/x/public_html/wp-load.php(50): require_once(‘/home/x…’)
#20 /home/x/public_html/wp-blog-header.php(13): require_once(‘/home/x…’)
#21 /home/x/public_html/index.php(17): require(‘/home/x…’)
#22 {main}
thrown
``` 

Customer said:
>Thus far it has only manifested as an email to me. I have not seen anything untoward on my screen or on my website.

**Expected behavior**
There should not be an error.

**Isolating the problem:**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro, Courses for Membership Add On, and plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

This came up in ticket 441951 and I can replicate it.

**WordPress Environment**
<details>
```
Paid Memberships Pro 2.9.3, Courses for Membership Add On 1.1, WordPress 6.0.1, PHP 8.1.8 and 8.2
```
</details>

**Comment by michaelbeil** [comment]
This was reported in ticket 433534.

**Comment by michaelbeil** [comment]
This was reported in ticket 448251 with PHP 8.0.22.
